version: '3.8'

services:
  ceph:
    image: ${CEPH_IMAGE_REPOSITORY}:${CEPH_IMAGE_TAG}
    user: root
    cap_add:
      - SYS_PTRACE
    privileged: true
    ports:
      - "6789:6789"
    volumes:
      - ./coverage.sh:/tmp/coverage.sh
      - ./ceph.conf:/etc/ceph/ceph.conf
      - /dev/sda3:/var/lib/ceph/osd/ceph-0
      - ./host.yml:/host.yml
    entrypoint: /bin/sleep infinity
    