version: '2'

services:
  rabbitmq:
    image: ${RABBITMQ_IMAGE_REPOSITORY}:${RABBITMQ_IMAGE_TAG}
    # privileged: true
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=bitnami
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    cap_add:
      - SYS_PTRACE
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'

volumes:
  rabbitmq_data:
    driver: local