version: '2'

services:
  fluentd:
    image: ${FLUENTD_IMAGE_REPOSITORY}:${FLUENTD_IMAGE_TAG}
    cap_add:
      - SYS_PTRACE
    ports:
      - '24224:24224'
      - '5140:5140'
    volumes:
      - fluentd_data:/fluentd/log
  backend1a:
    image: nginxdemos/hello:plain-text
    ports:
      - '80'
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: backend1a
  backend1b:
    image: nginxdemos/hello:plain-text
    ports:
      - '80'
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: backend1b
  backend2a:
    image: nginxdemos/hello:plain-text
    ports:
      - '80'
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: backend2a
  backend2b:
    image: nginxdemos/hello:plain-text
    ports:
      - '80'
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: backend2b
volumes:
  fluentd_data:
    driver: local
