version: '2'

services:
  redis-primary:
    image: ${REDIS_IMAGE_REPOSITORY}:${REDIS_IMAGE_TAG}
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=my_password
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis/data'
      - ../../common/tests/test.redis:/tmp/test.redis
      - ../../common/tests/redis_coverage.sh:/tmp/redis_coverage.sh
    cap_add:
      - SYS_PTRACE

  redis-secondary:
    image: ${REDIS_IMAGE_REPOSITORY}:${REDIS_IMAGE_TAG}
    ports:
      - '6379'
    depends_on:
      - redis-primary
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=my_password
      - REDIS_PASSWORD=my_password
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    cap_add:
      - SYS_PTRACE

volumes:
  redis_data:
    driver: local
