name: Image Scanner

on:
  schedule:
  - cron: '0 0 * * *'

  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    environment: actions-cicd
    steps:
      - uses: actions/checkout@v3
      - name: Setup ubuntu
        env:
          RF_ACCESS_ID: ${{ secrets.RF_ACCESS_ID }}
          RF_SECRET_ACCESS_KEY: ${{ secrets.RF_SECRET_ACCESS_KEY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./scripts/setup.sh
      - name: Scan images
        run: echo "rfscan scan_image.lst"
