name: MySQL DBT2 Benchmark Test Build

on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    environment: actions-cicd

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Import Coverage Tests
        uses: actions/checkout@v4
        with:
          repository: rapidfort/community-images-core
          token: ${{ secrets.COVERAGE_ACCESS_TOKEN }}
      - name: Docker login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_PASSWORD}"
      - name: Build docker image
        run: ./community_images/mysql/official/mysql_dbt2/build_docker.sh
